// Generated by `npm run demo:build` on 2026-08-31 from Music-And-Fx-Generated-Library.
// Do not edit by hand — rerun the script instead.
import type { DemoPack } from './demo-library.ts'

export const DEMO_PACKS: DemoPack[] = [
  {
    "id": "pack_ancient-discovery-level-i",
    "slug": "ancient-discovery-level-i",
    "title": "Ancient Discovery Level I",
    "description": "1 ambience beds from the Ancient Discovery set — ancient, ambient, awe-struck.",
    "kind": "ambience",
    "category": "ancient-discovery",
    "listingStatus": "draft",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": false,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/ancient-discovery-level-i/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_ancient-discovery-level-i_01",
        "name": "Instrumental Ancient Ambient Awe and Stillness",
        "durationSeconds": 40,
        "sortOrder": 0,
        "moods": [
          "ancient",
          "ambient",
          "awe-struck",
          "still"
        ],
        "instruments": [
          "orchestra",
          "strings"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_ancient-discovery-level-ii",
    "slug": "ancient-discovery-level-ii",
    "title": "Ancient Discovery Level II",
    "description": "1 ambience beds from the Ancient Discovery set — ancient, wonder, mysterious.",
    "kind": "ambience",
    "category": "ancient-discovery",
    "listingStatus": "draft",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": false,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/ancient-discovery-level-ii/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_ancient-discovery-level-ii_01",
        "name": "Instrumental Cinematic Ancient Wonder",
        "durationSeconds": 45,
        "sortOrder": 0,
        "moods": [
          "ancient",
          "wonder",
          "mysterious"
        ],
        "instruments": [
          "orchestra",
          "strings"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_ancient-discovery-level-iii",
    "slug": "ancient-discovery-level-iii",
    "title": "Ancient Discovery Level III",
    "description": "13 ambience beds from the Ancient Discovery set — epic, awe-struck.",
    "kind": "ambience",
    "category": "ancient-discovery",
    "listingStatus": "pending_review",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": false,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/ancient-discovery-level-iii/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_ancient-discovery-level-iii_01",
        "name": "Epic Orchestral Discovery Awe Struck",
        "durationSeconds": 40,
        "sortOrder": 0,
        "moods": [
          "epic",
          "awe-struck"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_ancient-discovery-level-iii_02",
        "name": "Epic Orchestral Discovery Awe Struck (2)",
        "durationSeconds": 40,
        "sortOrder": 1,
        "moods": [
          "epic",
          "awe-struck"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_ancient-discovery-level-iii_03",
        "name": "Epic Orchestral Discovery Awe Struck (3)",
        "durationSeconds": 40,
        "sortOrder": 2,
        "moods": [
          "epic",
          "awe-struck"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_ancient-discovery-level-iii_04",
        "name": "Epic Orchestral Discovery Awe Struck (4)",
        "durationSeconds": 40,
        "sortOrder": 3,
        "moods": [
          "epic",
          "awe-struck"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_ancient-discovery-level-iii_05",
        "name": "Epic Orchestral Discovery Awe Struck (5)",
        "durationSeconds": 40,
        "sortOrder": 4,
        "moods": [
          "epic",
          "awe-struck"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_ancient-discovery-level-iii_06",
        "name": "Epic Orchestral Discovery Awe Struck (6)",
        "durationSeconds": 40,
        "sortOrder": 5,
        "moods": [
          "epic",
          "awe-struck"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_ancient-discovery-level-iii_07",
        "name": "Epic Orchestral Discovery Awe Struck (7)",
        "durationSeconds": 40,
        "sortOrder": 6,
        "moods": [
          "epic",
          "awe-struck"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_ancient-discovery-level-iii_08",
        "name": "Epic Orchestral Discovery Awe Struck (8)",
        "durationSeconds": 40,
        "sortOrder": 7,
        "moods": [
          "epic",
          "awe-struck"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_ancient-discovery-level-iii_09",
        "name": "Epic Orchestral Discovery Awe Struck (9)",
        "durationSeconds": 40,
        "sortOrder": 8,
        "moods": [
          "epic",
          "awe-struck"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_ancient-discovery-level-iii_10",
        "name": "Epic Orchestral Discovery Awe Struck (10)",
        "durationSeconds": 40,
        "sortOrder": 9,
        "moods": [
          "epic",
          "awe-struck"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_ancient-discovery-level-iii_11",
        "name": "Epic Orchestral Discovery Awe Struck (11)",
        "durationSeconds": 40,
        "sortOrder": 10,
        "moods": [
          "epic",
          "awe-struck"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_ancient-discovery-level-iii_12",
        "name": "Epic Orchestral Discovery Awe Struck (12)",
        "durationSeconds": 40,
        "sortOrder": 11,
        "moods": [
          "epic",
          "awe-struck"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_ancient-discovery-level-iii_13",
        "name": "Epic Orchestral Discovery Awe Struck (13)",
        "durationSeconds": 40,
        "sortOrder": 12,
        "moods": [
          "epic",
          "awe-struck"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_beast-hunt-i",
    "slug": "beast-hunt-i",
    "title": "Beast Hunt I",
    "description": "30 ambience beds from the Beast Hunt set — ambient, serene, coiled.",
    "kind": "ambience",
    "category": "beast-hunt",
    "listingStatus": "live",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": true,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/beast-hunt-i/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_beast-hunt-i_01",
        "name": "Instrumental Beast Hunt Ambient Serene",
        "durationSeconds": 110,
        "sortOrder": 0,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": "packs/beast-hunt-i/v/v1/tracks/track_beast-hunt-i_01.ogg"
      },
      {
        "id": "track_beast-hunt-i_02",
        "name": "Instrumental Beast Hunt Ambient Serene (2)",
        "durationSeconds": 120,
        "sortOrder": 1,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_03",
        "name": "Instrumental Beast Hunt Ambient Serene (3)",
        "durationSeconds": 120,
        "sortOrder": 2,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_04",
        "name": "Instrumental Beast Hunt Ambient Serene (4)",
        "durationSeconds": 120,
        "sortOrder": 3,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_05",
        "name": "Instrumental Beast Hunt Ambient Serene (5)",
        "durationSeconds": 120,
        "sortOrder": 4,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_06",
        "name": "Instrumental Beast Hunt Ambient Serene (6)",
        "durationSeconds": 120,
        "sortOrder": 5,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_07",
        "name": "Instrumental Beast Hunt Ambient Serene (7)",
        "durationSeconds": 120,
        "sortOrder": 6,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_08",
        "name": "Instrumental Beast Hunt Ambient Serene (8)",
        "durationSeconds": 120,
        "sortOrder": 7,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_09",
        "name": "Instrumental Beast Hunt Ambient Serene (9)",
        "durationSeconds": 120,
        "sortOrder": 8,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_10",
        "name": "Instrumental Beast Hunt Ambient Serene (10)",
        "durationSeconds": 120,
        "sortOrder": 9,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_11",
        "name": "Instrumental Beast Hunt Ambient Serene (11)",
        "durationSeconds": 120,
        "sortOrder": 10,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_12",
        "name": "Instrumental Beast Hunt Ambient Serene (12)",
        "durationSeconds": 120,
        "sortOrder": 11,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_13",
        "name": "Instrumental Beast Hunt Ambient Serene (13)",
        "durationSeconds": 120,
        "sortOrder": 12,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_14",
        "name": "Instrumental Beast Hunt Ambient Serene (14)",
        "durationSeconds": 120,
        "sortOrder": 13,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_15",
        "name": "Instrumental Beast Hunt Ambient Serene (15)",
        "durationSeconds": 120,
        "sortOrder": 14,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_16",
        "name": "Instrumental Beast Hunt Ambient Serene (16)",
        "durationSeconds": 120,
        "sortOrder": 15,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_17",
        "name": "Instrumental Beast Hunt Ambient Serene (17)",
        "durationSeconds": 120,
        "sortOrder": 16,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_18",
        "name": "Instrumental Beast Hunt Ambient Serene (18)",
        "durationSeconds": 120,
        "sortOrder": 17,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_19",
        "name": "Instrumental Beast Hunt Ambient Serene (19)",
        "durationSeconds": 120,
        "sortOrder": 18,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_20",
        "name": "Instrumental Beast Hunt Ambient Serene (20)",
        "durationSeconds": 95,
        "sortOrder": 19,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_21",
        "name": "Instrumental Blind and Wait Ambient Coiled",
        "durationSeconds": 120,
        "sortOrder": 20,
        "moods": [
          "ambient",
          "coiled"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_22",
        "name": "Instrumental Broken Branch Ambient Alert",
        "durationSeconds": 120,
        "sortOrder": 21,
        "moods": [
          "ambient",
          "alert"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_23",
        "name": "Instrumental First Sighting Ambient Breath",
        "durationSeconds": 120,
        "sortOrder": 22,
        "moods": [
          "ambient"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_24",
        "name": "Instrumental Hunt Tracking Ambient Patient",
        "durationSeconds": 90,
        "sortOrder": 23,
        "moods": [
          "ambient",
          "patient"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_25",
        "name": "Instrumental Marsh Trail Ambient Sucking",
        "durationSeconds": 120,
        "sortOrder": 24,
        "moods": [
          "ambient"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_26",
        "name": "Instrumental Night Track Ambient Tense and Dim",
        "durationSeconds": 120,
        "sortOrder": 25,
        "moods": [
          "ambient"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_27",
        "name": "Instrumental Old Kill Site Ambient Grim",
        "durationSeconds": 120,
        "sortOrder": 26,
        "moods": [
          "ambient",
          "grim"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_28",
        "name": "Instrumental Ridge Glassing Ambient Watchful",
        "durationSeconds": 120,
        "sortOrder": 27,
        "moods": [
          "ambient",
          "watchful"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_29",
        "name": "Instrumental Scent of It Ambient Uneasy",
        "durationSeconds": 120,
        "sortOrder": 28,
        "moods": [
          "ambient"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-i_30",
        "name": "Instrumental Spoor Ambient Quiet and Grim",
        "durationSeconds": 120,
        "sortOrder": 29,
        "moods": [
          "ambient",
          "quiet",
          "grim"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_beast-hunt-ii",
    "slug": "beast-hunt-ii",
    "title": "Beast Hunt II",
    "description": "30 ambience beds from the Beast Hunt set — adventurous, prowling, exposed.",
    "kind": "ambience",
    "category": "beast-hunt",
    "listingStatus": "live",
    "priceSnapshotCents": 900,
    "priceUpdatePassCents": 1400,
    "featuredEligible": true,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/beast-hunt-ii/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_beast-hunt-ii_01",
        "name": "Instrumental Beast Hunt Movement Adventurous",
        "durationSeconds": 105,
        "sortOrder": 0,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": "packs/beast-hunt-ii/v/v1/tracks/track_beast-hunt-ii_01.ogg"
      },
      {
        "id": "track_beast-hunt-ii_02",
        "name": "Instrumental Beast Hunt Movement Adventurous (2)",
        "durationSeconds": 115,
        "sortOrder": 1,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_03",
        "name": "Instrumental Beast Hunt Movement Adventurous (3)",
        "durationSeconds": 120,
        "sortOrder": 2,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_04",
        "name": "Instrumental Beast Hunt Movement Adventurous (4)",
        "durationSeconds": 120,
        "sortOrder": 3,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_05",
        "name": "Instrumental Beast Hunt Movement Adventurous (5)",
        "durationSeconds": 120,
        "sortOrder": 4,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_06",
        "name": "Instrumental Beast Hunt Movement Adventurous (6)",
        "durationSeconds": 120,
        "sortOrder": 5,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_07",
        "name": "Instrumental Beast Hunt Movement Adventurous (7)",
        "durationSeconds": 120,
        "sortOrder": 6,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_08",
        "name": "Instrumental Beast Hunt Movement Adventurous (8)",
        "durationSeconds": 120,
        "sortOrder": 7,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_09",
        "name": "Instrumental Beast Hunt Movement Adventurous (9)",
        "durationSeconds": 120,
        "sortOrder": 8,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_10",
        "name": "Instrumental Beast Hunt Movement Adventurous (10)",
        "durationSeconds": 120,
        "sortOrder": 9,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_11",
        "name": "Instrumental Beast Hunt Movement Adventurous (11)",
        "durationSeconds": 120,
        "sortOrder": 10,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_12",
        "name": "Instrumental Beast Hunt Movement Adventurous (12)",
        "durationSeconds": 120,
        "sortOrder": 11,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_13",
        "name": "Instrumental Beast Hunt Movement Adventurous (13)",
        "durationSeconds": 120,
        "sortOrder": 12,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_14",
        "name": "Instrumental Beast Hunt Movement Adventurous (14)",
        "durationSeconds": 120,
        "sortOrder": 13,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_15",
        "name": "Instrumental Beast Hunt Movement Adventurous (15)",
        "durationSeconds": 120,
        "sortOrder": 14,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_16",
        "name": "Instrumental Beast Hunt Movement Adventurous (16)",
        "durationSeconds": 50,
        "sortOrder": 15,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_17",
        "name": "Instrumental Beast Hunt Movement Adventurous (17)",
        "durationSeconds": 65,
        "sortOrder": 16,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_18",
        "name": "Instrumental Beast Hunt Movement Adventurous (18)",
        "durationSeconds": 70,
        "sortOrder": 17,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_19",
        "name": "Instrumental Beast Hunt Movement Adventurous (19)",
        "durationSeconds": 80,
        "sortOrder": 18,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_20",
        "name": "Instrumental Beast Hunt Movement Adventurous (20)",
        "durationSeconds": 95,
        "sortOrder": 19,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_21",
        "name": "Instrumental Beast Hunt Orchestral Prowling",
        "durationSeconds": 45,
        "sortOrder": 20,
        "moods": [
          "prowling"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_22",
        "name": "Instrumental Cliff Track Orchestral Exposed",
        "durationSeconds": 120,
        "sortOrder": 21,
        "moods": [
          "exposed"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_23",
        "name": "Instrumental Closing Circle Orchestral",
        "durationSeconds": 120,
        "sortOrder": 22,
        "moods": [
          "tense",
          "driving"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_24",
        "name": "Instrumental False Lair Orchestral Suspicious",
        "durationSeconds": 120,
        "sortOrder": 23,
        "moods": [
          "tense",
          "driving"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_25",
        "name": "Instrumental Flushing Drive Orchestral",
        "durationSeconds": 60,
        "sortOrder": 24,
        "moods": [
          "tense",
          "driving"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_26",
        "name": "Instrumental Night Hunt Orchestral Hushed",
        "durationSeconds": 120,
        "sortOrder": 25,
        "moods": [
          "hushed"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_27",
        "name": "Instrumental Pack Signs Orchestral Grim",
        "durationSeconds": 120,
        "sortOrder": 26,
        "moods": [
          "grim"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_28",
        "name": "Instrumental River Crossing Pursuit Surging",
        "durationSeconds": 90,
        "sortOrder": 27,
        "moods": [
          "tense",
          "driving"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_29",
        "name": "Instrumental Roar in the Dark Orchestral",
        "durationSeconds": 120,
        "sortOrder": 28,
        "moods": [
          "dark"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-ii_30",
        "name": "Instrumental Wounded Quarry Orchestral Wary",
        "durationSeconds": 75,
        "sortOrder": 29,
        "moods": [
          "tense",
          "driving"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_beast-hunt-iii",
    "slug": "beast-hunt-iii",
    "title": "Beast Hunt III",
    "description": "30 ambience beds from the Beast Hunt set — climactic, epic, monumental.",
    "kind": "ambience",
    "category": "beast-hunt",
    "listingStatus": "live",
    "priceSnapshotCents": 1200,
    "priceUpdatePassCents": 1800,
    "featuredEligible": true,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/beast-hunt-iii/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_beast-hunt-iii_01",
        "name": "Beast Hunt Climax Epic and Monumental Blaring",
        "durationSeconds": 120,
        "sortOrder": 0,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "blaring"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": "packs/beast-hunt-iii/v/v1/tracks/track_beast-hunt-iii_01.ogg"
      },
      {
        "id": "track_beast-hunt-iii_02",
        "name": "Beast Hunt Climax Epic and Monumental Blaring (2)",
        "durationSeconds": 65,
        "sortOrder": 1,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "blaring"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_03",
        "name": "Beast Hunt Climax Epic and Monumental Blaring (3)",
        "durationSeconds": 120,
        "sortOrder": 2,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "blaring"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_04",
        "name": "Beast Hunt Climax Epic and Monumental Blaring (4)",
        "durationSeconds": 120,
        "sortOrder": 3,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "blaring"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_05",
        "name": "Beast Hunt Climax Epic and Monumental Driving",
        "durationSeconds": 120,
        "sortOrder": 4,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "driving"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_06",
        "name": "Beast Hunt Climax Epic and Monumental Driving (2)",
        "durationSeconds": 90,
        "sortOrder": 5,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "driving"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_07",
        "name": "Beast Hunt Climax Epic and Monumental Full",
        "durationSeconds": 120,
        "sortOrder": 6,
        "moods": [
          "climactic",
          "epic",
          "monumental"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_08",
        "name": "Beast Hunt Climax Epic and Monumental Full (2)",
        "durationSeconds": 120,
        "sortOrder": 7,
        "moods": [
          "climactic",
          "epic",
          "monumental"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_09",
        "name": "Beast Hunt Climax Epic and Monumental Furious",
        "durationSeconds": 120,
        "sortOrder": 8,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "furious"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_10",
        "name": "Beast Hunt Climax Epic and Monumental Furious (2)",
        "durationSeconds": 120,
        "sortOrder": 9,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "furious"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_11",
        "name": "Beast Hunt Climax Epic and Monumental Massive",
        "durationSeconds": 120,
        "sortOrder": 10,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "massive"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_12",
        "name": "Beast Hunt Climax Epic and Monumental Massive (2)",
        "durationSeconds": 75,
        "sortOrder": 11,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "massive"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_13",
        "name": "Beast Hunt Climax Epic and Monumental Roaring",
        "durationSeconds": 120,
        "sortOrder": 12,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "roaring"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_14",
        "name": "Beast Hunt Climax Epic and Monumental Roaring (2)",
        "durationSeconds": 120,
        "sortOrder": 13,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "roaring"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_15",
        "name": "Beast Hunt Climax Epic and Monumental Sweeping",
        "durationSeconds": 120,
        "sortOrder": 14,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "sweeping"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_16",
        "name": "Beast Hunt Climax Epic and Monumental Sweeping (2)",
        "durationSeconds": 55,
        "sortOrder": 15,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "sweeping"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_17",
        "name": "Beast Hunt Climax Epic and Monumental",
        "durationSeconds": 120,
        "sortOrder": 16,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "thunderous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_18",
        "name": "Beast Hunt Climax Epic and Monumental (2)",
        "durationSeconds": 45,
        "sortOrder": 17,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "thunderous"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_19",
        "name": "Beast Hunt Climax Epic and Monumental Towering",
        "durationSeconds": 105,
        "sortOrder": 18,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "towering"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_20",
        "name": "Beast Hunt Climax Epic and Monumental Towering (2)",
        "durationSeconds": 120,
        "sortOrder": 19,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "towering"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_21",
        "name": "Instrumental Alpha Duel Orchestral Titanic",
        "durationSeconds": 120,
        "sortOrder": 20,
        "moods": [
          "tense",
          "driving"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_22",
        "name": "Instrumental Beast Charge Orchestral Ferocious",
        "durationSeconds": 40,
        "sortOrder": 21,
        "moods": [
          "tense",
          "driving"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_23",
        "name": "Instrumental Bog Takedown Orchestral Heaving",
        "durationSeconds": 120,
        "sortOrder": 22,
        "moods": [
          "tense",
          "driving"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_24",
        "name": "Instrumental Chase Reversed Orchestral",
        "durationSeconds": 120,
        "sortOrder": 23,
        "moods": [
          "tense",
          "driving"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_25",
        "name": "Instrumental Cliff Fall Finale Plunging",
        "durationSeconds": 120,
        "sortOrder": 24,
        "moods": [
          "tense",
          "driving"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_26",
        "name": "Instrumental Deathmatch Orchestral Brutal",
        "durationSeconds": 60,
        "sortOrder": 25,
        "moods": [
          "tense",
          "driving"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_27",
        "name": "Instrumental Horn of Triumph Hunt Ending",
        "durationSeconds": 120,
        "sortOrder": 26,
        "moods": [
          "tense",
          "driving"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_28",
        "name": "Instrumental Night Gore Orchestral Chaotic",
        "durationSeconds": 120,
        "sortOrder": 27,
        "moods": [
          "tense",
          "driving"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_29",
        "name": "Instrumental Treed and Furious Orchestral",
        "durationSeconds": 90,
        "sortOrder": 28,
        "moods": [
          "furious"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_beast-hunt-iii_30",
        "name": "Legend Beast Finale Awed Ferocity Massive",
        "durationSeconds": 120,
        "sortOrder": 29,
        "moods": [
          "massive"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_beast-hunt-level-i",
    "slug": "beast-hunt-level-i",
    "title": "Beast Hunt Level I",
    "description": "1 ambience beds from the Beast Hunt set — ambient, patient.",
    "kind": "ambience",
    "category": "beast-hunt",
    "listingStatus": "draft",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": false,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/beast-hunt-level-i/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_beast-hunt-level-i_01",
        "name": "Instrumental Hunt Tracking Ambient Patient",
        "durationSeconds": 102,
        "sortOrder": 0,
        "moods": [
          "ambient",
          "patient"
        ],
        "instruments": [
          "orchestra",
          "percussion"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_boss-i",
    "slug": "boss-i",
    "title": "Boss I",
    "description": "2 ambience beds from the Boss set — dark, tense, ominous.",
    "kind": "ambience",
    "category": "boss",
    "listingStatus": "draft",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": false,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/boss-i/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_boss-i_01",
        "name": "Instrumental Dark Orchestral Tension Ominous",
        "durationSeconds": 90,
        "sortOrder": 0,
        "moods": [
          "dark",
          "tense",
          "ominous"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_boss-i_02",
        "name": "Instrumental Dark Orchestral Tension Ominous (2)",
        "durationSeconds": 90,
        "sortOrder": 1,
        "moods": [
          "dark",
          "tense",
          "ominous"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_boss-level-i",
    "slug": "boss-level-i",
    "title": "Boss Level I",
    "description": "1 ambience beds from the Boss set — dark, tense, ominous.",
    "kind": "ambience",
    "category": "boss",
    "listingStatus": "draft",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": false,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/boss-level-i/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_boss-level-i_01",
        "name": "Instrumental Dark Orchestral Tension Ominous",
        "durationSeconds": 90,
        "sortOrder": 0,
        "moods": [
          "dark",
          "tense",
          "ominous"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_city-level-iii",
    "slug": "city-level-iii",
    "title": "City Level III",
    "description": "1 ambience beds from the City set — epic, awe-struck, monumental.",
    "kind": "ambience",
    "category": "city",
    "listingStatus": "draft",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": false,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/city-level-iii/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_city-level-iii_01",
        "name": "Epic Orchestral Disco Awe Struck",
        "durationSeconds": 40,
        "sortOrder": 0,
        "moods": [
          "epic",
          "awe-struck",
          "monumental"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_custom-demo",
    "slug": "custom-demo",
    "title": "Custom Demo",
    "description": "21 ambience beds from the Custom set — ambient, intimate, dreadful.",
    "kind": "ambience",
    "category": "custom",
    "listingStatus": "pending_review",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": false,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/custom-demo/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_custom-demo_01",
        "name": "Dreams Visited Ambient Intimate and Violating",
        "durationSeconds": 120,
        "sortOrder": 0,
        "moods": [
          "ambient",
          "intimate"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_02",
        "name": "Instrumental Coronation of the Enemy Piece",
        "durationSeconds": 60,
        "sortOrder": 1,
        "moods": [
          "dreadful"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_03",
        "name": "Instrumental Patronage Ambient Generous",
        "durationSeconds": 120,
        "sortOrder": 2,
        "moods": [
          "ambient"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_04",
        "name": "Instrumental Portrait in the Hall Ambient",
        "durationSeconds": 120,
        "sortOrder": 3,
        "moods": [
          "ambient"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_05",
        "name": "Instrumental Recruitment Offer Piece Seductive",
        "durationSeconds": 120,
        "sortOrder": 4,
        "moods": [
          "seductive"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_06",
        "name": "Instrumental Ritual Completed Piece",
        "durationSeconds": 120,
        "sortOrder": 5,
        "moods": [
          "apocalyptic"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_07",
        "name": "Instrumental Timeworn Ambient Hushed Reverence",
        "durationSeconds": 120,
        "sortOrder": 6,
        "moods": [
          "timeworn",
          "ambient",
          "hushed",
          "reverent"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_08",
        "name": "Instrumental Villain Influence Ambient Elegant",
        "durationSeconds": 90,
        "sortOrder": 7,
        "moods": [
          "ambient",
          "elegant"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_09",
        "name": "Instrumental Villain Theme Ambient Serene",
        "durationSeconds": 120,
        "sortOrder": 8,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_10",
        "name": "Instrumental Villain Theme Ambient Serene (2)",
        "durationSeconds": 95,
        "sortOrder": 9,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_11",
        "name": "Instrumental Villain Theme Movement",
        "durationSeconds": 120,
        "sortOrder": 10,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_12",
        "name": "Instrumental Villain Theme Movement (2)",
        "durationSeconds": 120,
        "sortOrder": 11,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_13",
        "name": "Villain Theme Climax Epic and Monumental",
        "durationSeconds": 120,
        "sortOrder": 12,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "blaring"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_14",
        "name": "Villain Theme Climax Epic and Monumental (2)",
        "durationSeconds": 65,
        "sortOrder": 13,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "blaring"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_15",
        "name": "Villain Theme Climax Epic and Monumental (3)",
        "durationSeconds": 120,
        "sortOrder": 14,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "massive"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_16",
        "name": "Villain Theme Climax Epic and Monumental (4)",
        "durationSeconds": 75,
        "sortOrder": 15,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "massive"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_17",
        "name": "Villain Theme Climax Epic and Monumental (5)",
        "durationSeconds": 120,
        "sortOrder": 16,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "roaring"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_18",
        "name": "Villain Theme Climax Epic and Monumental (6)",
        "durationSeconds": 120,
        "sortOrder": 17,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "roaring"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_19",
        "name": "Villain Theme Climax Epic and Monumental (7)",
        "durationSeconds": 55,
        "sortOrder": 18,
        "moods": [
          "climactic",
          "epic",
          "monumental"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_20",
        "name": "Villain Theme Climax Epic and Monumental (8)",
        "durationSeconds": 120,
        "sortOrder": 19,
        "moods": [
          "climactic",
          "epic",
          "monumental"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-demo_21",
        "name": "Villain Triumphant Orchestral Magnificent",
        "durationSeconds": 40,
        "sortOrder": 20,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_custom-level-i",
    "slug": "custom-level-i",
    "title": "Custom Level I",
    "description": "44 ambience beds from the Custom set — ambient, intimate, quiet.",
    "kind": "ambience",
    "category": "custom",
    "listingStatus": "live",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": true,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/custom-level-i/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_custom-level-i_01",
        "name": "Dreams Visited Ambient Intimate and Violating",
        "durationSeconds": 120,
        "sortOrder": 0,
        "moods": [
          "ambient",
          "intimate"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": "packs/custom-level-i/v/v1/tracks/track_custom-level-i_01.ogg"
      },
      {
        "id": "track_custom-level-i_02",
        "name": "Instrumental Agents Everywhere Ambient Quiet",
        "durationSeconds": 120,
        "sortOrder": 1,
        "moods": [
          "ambient",
          "quiet"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_03",
        "name": "Instrumental Ancient Ambient Awe and Stillness",
        "durationSeconds": 90,
        "sortOrder": 2,
        "moods": [
          "ancient",
          "ambient",
          "awe-struck",
          "still"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_04",
        "name": "Instrumental Army Unveiled Piece Thunderous",
        "durationSeconds": 120,
        "sortOrder": 3,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_05",
        "name": "Instrumental Bargain with Heroes Piece",
        "durationSeconds": 120,
        "sortOrder": 4,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_06",
        "name": "Instrumental Betrayal Repaid Piece Savage",
        "durationSeconds": 120,
        "sortOrder": 5,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_07",
        "name": "Instrumental Charm Offensive Piece Gorgeous",
        "durationSeconds": 60,
        "sortOrder": 6,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_08",
        "name": "Instrumental Checkmate Piece Precise and Huge",
        "durationSeconds": 90,
        "sortOrder": 7,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_09",
        "name": "Instrumental Chess Moves Ambient Patient",
        "durationSeconds": 120,
        "sortOrder": 8,
        "moods": [
          "ambient",
          "patient"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_10",
        "name": "Instrumental City Kneels Piece Imperial",
        "durationSeconds": 120,
        "sortOrder": 9,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_11",
        "name": "Instrumental Coronation of the Enemy Piece",
        "durationSeconds": 60,
        "sortOrder": 10,
        "moods": [
          "dreadful"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_12",
        "name": "Instrumental Demonstration of Power Piece",
        "durationSeconds": 90,
        "sortOrder": 11,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_13",
        "name": "Instrumental Departure Piece Unhurried",
        "durationSeconds": 120,
        "sortOrder": 12,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_14",
        "name": "Instrumental Empty Chair at Council Ambient",
        "durationSeconds": 120,
        "sortOrder": 13,
        "moods": [
          "ambient"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_15",
        "name": "Instrumental First Glimpse Ambient Breath",
        "durationSeconds": 120,
        "sortOrder": 14,
        "moods": [
          "ambient"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_16",
        "name": "Instrumental Hero Broken Piece Crushing",
        "durationSeconds": 120,
        "sortOrder": 15,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_17",
        "name": "Instrumental Inspection of the Works Piece",
        "durationSeconds": 120,
        "sortOrder": 16,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_18",
        "name": "Instrumental Mask Almost Slips Piece Elegant",
        "durationSeconds": 120,
        "sortOrder": 17,
        "moods": [
          "elegant"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_19",
        "name": "Instrumental Monologue at the Summit Piece",
        "durationSeconds": 120,
        "sortOrder": 18,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_20",
        "name": "Instrumental Monologue Piece Articulate Menace",
        "durationSeconds": 75,
        "sortOrder": 19,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_21",
        "name": "Instrumental Old Wound of the Realm Ambient",
        "durationSeconds": 120,
        "sortOrder": 20,
        "moods": [
          "ambient"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_22",
        "name": "Instrumental Patronage Ambient Generous",
        "durationSeconds": 120,
        "sortOrder": 21,
        "moods": [
          "ambient"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_23",
        "name": "Instrumental Portrait in the Hall Ambient",
        "durationSeconds": 120,
        "sortOrder": 22,
        "moods": [
          "ambient"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_24",
        "name": "Instrumental Recruitment Offer Piece Seductive",
        "durationSeconds": 120,
        "sortOrder": 23,
        "moods": [
          "seductive"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_25",
        "name": "Instrumental Ritual Completed Piece",
        "durationSeconds": 120,
        "sortOrder": 24,
        "moods": [
          "apocalyptic"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_26",
        "name": "Instrumental Rivals Dismissed Piece",
        "durationSeconds": 120,
        "sortOrder": 25,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_27",
        "name": "Instrumental Shadow Over the Map Coda",
        "durationSeconds": 120,
        "sortOrder": 26,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_28",
        "name": "Instrumental Terms Delivered Ambient Courteous",
        "durationSeconds": 120,
        "sortOrder": 27,
        "moods": [
          "ambient"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_29",
        "name": "Instrumental Timeworn Ambient Hushed Reverence",
        "durationSeconds": 120,
        "sortOrder": 28,
        "moods": [
          "timeworn",
          "ambient",
          "hushed",
          "reverent"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_30",
        "name": "Instrumental Timeworn Ambient Hushed Reverence (2)",
        "durationSeconds": 120,
        "sortOrder": 29,
        "moods": [
          "timeworn",
          "ambient",
          "hushed",
          "reverent"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_31",
        "name": "Instrumental Villain Influence Ambient Elegant",
        "durationSeconds": 90,
        "sortOrder": 30,
        "moods": [
          "ambient",
          "elegant"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_32",
        "name": "Instrumental Villain Theme Ambient Serene",
        "durationSeconds": 120,
        "sortOrder": 31,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_33",
        "name": "Instrumental Villain Theme Ambient Serene (2)",
        "durationSeconds": 95,
        "sortOrder": 32,
        "moods": [
          "ambient",
          "serene"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_34",
        "name": "Instrumental Villain Theme Movement",
        "durationSeconds": 120,
        "sortOrder": 33,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_35",
        "name": "Instrumental Villain Theme Movement (2)",
        "durationSeconds": 120,
        "sortOrder": 34,
        "moods": [
          "adventurous"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_36",
        "name": "Villain Theme Climax Epic and Monumental",
        "durationSeconds": 120,
        "sortOrder": 35,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "blaring"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_37",
        "name": "Villain Theme Climax Epic and Monumental (2)",
        "durationSeconds": 65,
        "sortOrder": 36,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "blaring"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_38",
        "name": "Villain Theme Climax Epic and Monumental (3)",
        "durationSeconds": 120,
        "sortOrder": 37,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "massive"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_39",
        "name": "Villain Theme Climax Epic and Monumental (4)",
        "durationSeconds": 75,
        "sortOrder": 38,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "massive"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_40",
        "name": "Villain Theme Climax Epic and Monumental (5)",
        "durationSeconds": 120,
        "sortOrder": 39,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "roaring"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_41",
        "name": "Villain Theme Climax Epic and Monumental (6)",
        "durationSeconds": 120,
        "sortOrder": 40,
        "moods": [
          "climactic",
          "epic",
          "monumental",
          "roaring"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_42",
        "name": "Villain Theme Climax Epic and Monumental (7)",
        "durationSeconds": 55,
        "sortOrder": 41,
        "moods": [
          "climactic",
          "epic",
          "monumental"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_43",
        "name": "Villain Theme Climax Epic and Monumental (8)",
        "durationSeconds": 120,
        "sortOrder": 42,
        "moods": [
          "climactic",
          "epic",
          "monumental"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-i_44",
        "name": "Villain Triumphant Orchestral Magnificent",
        "durationSeconds": 40,
        "sortOrder": 43,
        "moods": [
          "varied"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_custom-level-iii",
    "slug": "custom-level-iii",
    "title": "Custom Level III",
    "description": "9 ambience beds from the Custom set — epic.",
    "kind": "ambience",
    "category": "custom",
    "listingStatus": "draft",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": false,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/custom-level-iii/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_custom-level-iii_01",
        "name": "Epic Disco",
        "durationSeconds": 40,
        "sortOrder": 0,
        "moods": [
          "epic"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-iii_02",
        "name": "Epic Disco (2)",
        "durationSeconds": 9,
        "sortOrder": 1,
        "moods": [
          "epic"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-iii_03",
        "name": "Epic Disco (3)",
        "durationSeconds": 9,
        "sortOrder": 2,
        "moods": [
          "epic"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-iii_04",
        "name": "Epic Disco (4)",
        "durationSeconds": 9,
        "sortOrder": 3,
        "moods": [
          "epic"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-iii_05",
        "name": "Epic Disco (5)",
        "durationSeconds": 9,
        "sortOrder": 4,
        "moods": [
          "epic"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-iii_06",
        "name": "Epic Disco Loop",
        "durationSeconds": 9,
        "sortOrder": 5,
        "moods": [
          "epic"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-iii_07",
        "name": "Epic Disco Loop (2)",
        "durationSeconds": 9,
        "sortOrder": 6,
        "moods": [
          "epic"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-iii_08",
        "name": "Epic Disco Loop (3)",
        "durationSeconds": 9,
        "sortOrder": 7,
        "moods": [
          "epic"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_custom-level-iii_09",
        "name": "Epic Disco Loop (4)",
        "durationSeconds": 9,
        "sortOrder": 8,
        "moods": [
          "epic"
        ],
        "instruments": [
          "orchestra"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_dungeon",
    "slug": "dungeon",
    "title": "Dungeon",
    "description": "7 ambience beds from the Dungeon set — tense, dark, slow.",
    "kind": "ambience",
    "category": "dungeon",
    "listingStatus": "draft",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": false,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/dungeon/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_dungeon_01",
        "name": "Cavern Ceiling Drips into a Pool 1 Drop",
        "durationSeconds": 57,
        "sortOrder": 0,
        "moods": [
          "tense",
          "dark"
        ],
        "instruments": [
          "cave tone",
          "water"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_dungeon_02",
        "name": "Cavern Ceiling Drips into a Pool 1 Drop (2)",
        "durationSeconds": 56,
        "sortOrder": 1,
        "moods": [
          "tense",
          "dark"
        ],
        "instruments": [
          "cave tone",
          "water"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_dungeon_03",
        "name": "Cavern Ceiling Drips into a Pool Large Cave",
        "durationSeconds": 120,
        "sortOrder": 2,
        "moods": [
          "tense",
          "dark"
        ],
        "instruments": [
          "cave tone",
          "water"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_dungeon_04",
        "name": "Cavern Ceiling Drips into a Pool Large Cave (2)",
        "durationSeconds": 120,
        "sortOrder": 3,
        "moods": [
          "tense",
          "dark"
        ],
        "instruments": [
          "cave tone",
          "water"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_dungeon_05",
        "name": "Cavern Ceiling Drips into a Pool Very",
        "durationSeconds": 57,
        "sortOrder": 4,
        "moods": [
          "tense",
          "dark"
        ],
        "instruments": [
          "cave tone",
          "water"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_dungeon_06",
        "name": "Limestone Cavern Ceiling Drips into a Pool",
        "durationSeconds": 120,
        "sortOrder": 5,
        "moods": [
          "tense",
          "dark"
        ],
        "instruments": [
          "cave tone",
          "water"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_dungeon_07",
        "name": "Very Slow Cavern Ceiling Drips into a Pool",
        "durationSeconds": 120,
        "sortOrder": 6,
        "moods": [
          "slow"
        ],
        "instruments": [
          "cave tone",
          "water"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_fx-combat-axe-blunt",
    "slug": "fx-combat-axe-blunt",
    "title": "Combat Axe & Blunt",
    "description": "3 FX one-shots from the Combat set — heavy.",
    "kind": "fx",
    "category": "combat",
    "listingStatus": "draft",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": false,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/fx-combat-axe-blunt/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_fx-combat-axe-blunt_01",
        "name": "Heavy Iron Axe Cutting",
        "durationSeconds": 2,
        "sortOrder": 0,
        "moods": [
          "heavy"
        ],
        "instruments": [
          "iron",
          "axe"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_fx-combat-axe-blunt_02",
        "name": "Heavy Iron Axe Cutting Air then Biting Wood",
        "durationSeconds": 2,
        "sortOrder": 1,
        "moods": [
          "heavy"
        ],
        "instruments": [
          "iron",
          "axe",
          "wood"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_fx-combat-axe-blunt_03",
        "name": "Heavy Iron Axe Cutting Air then Biting Wood (2)",
        "durationSeconds": 2,
        "sortOrder": 2,
        "moods": [
          "heavy"
        ],
        "instruments": [
          "iron",
          "axe",
          "wood"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_fx-creatures-bites-attacks",
    "slug": "fx-creatures-bites-attacks",
    "title": "Creatures Bites & Attacks",
    "description": "3 FX one-shots from the Creatures set — heavy.",
    "kind": "fx",
    "category": "creatures",
    "listingStatus": "draft",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": false,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/fx-creatures-bites-attacks/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_fx-creatures-bites-attacks_01",
        "name": "Heavy Segmented Chitin Tail Whipping Forward",
        "durationSeconds": 2,
        "sortOrder": 0,
        "moods": [
          "heavy"
        ],
        "instruments": [
          "chitin"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_fx-creatures-bites-attacks_02",
        "name": "Heavy Segmented Chitin Tail Whipping Forward (2)",
        "durationSeconds": 2,
        "sortOrder": 1,
        "moods": [
          "heavy"
        ],
        "instruments": [
          "chitin"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_fx-creatures-bites-attacks_03",
        "name": "Heavy Segmented Chitin Tail Whipping Forward (3)",
        "durationSeconds": 2,
        "sortOrder": 2,
        "moods": [
          "heavy"
        ],
        "instruments": [
          "chitin"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_fx-custom",
    "slug": "fx-custom",
    "title": "Custom FX",
    "description": "5 FX one-shots from the Custom set — violent, varied, bright.",
    "kind": "fx",
    "category": "custom",
    "listingStatus": "draft",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": false,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/fx-custom/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_fx-custom_01",
        "name": "Alchemical Mixture Boiling Violently",
        "durationSeconds": 3,
        "sortOrder": 0,
        "moods": [
          "violent"
        ],
        "instruments": [
          "liquid"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_fx-custom_02",
        "name": "Alchemical Mixture Boiling Violently (2)",
        "durationSeconds": 3,
        "sortOrder": 1,
        "moods": [
          "violent"
        ],
        "instruments": [
          "liquid"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_fx-custom_03",
        "name": "Clean UI Confirm Chime",
        "durationSeconds": 1,
        "sortOrder": 2,
        "moods": [
          "varied"
        ],
        "instruments": [
          "chimes"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_fx-custom_04",
        "name": "Clean UI Confirm Chime Two Short Bright Tones",
        "durationSeconds": 1,
        "sortOrder": 3,
        "moods": [
          "bright"
        ],
        "instruments": [
          "chimes",
          "tones"
        ],
        "fullKey": null,
        "previewKey": null
      },
      {
        "id": "track_fx-custom_05",
        "name": "Thick Viscous Potion Gently Bubbling in Heavy",
        "durationSeconds": 3,
        "sortOrder": 4,
        "moods": [
          "gentle",
          "heavy"
        ],
        "instruments": [
          "liquid"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  },
  {
    "id": "pack_winter-level-i",
    "slug": "winter-level-i",
    "title": "Winter Level I",
    "description": "1 ambience beds from the Winter set — quiet, still.",
    "kind": "ambience",
    "category": "winter",
    "listingStatus": "draft",
    "priceSnapshotCents": 0,
    "priceUpdatePassCents": 0,
    "featuredEligible": false,
    "version": "v1",
    "changelog": "Initial curated release",
    "zipKey": "packs/winter-level-i/v/v1/pack.zip",
    "tracks": [
      {
        "id": "track_winter-level-i_01",
        "name": "Winter Snowing",
        "durationSeconds": 9,
        "sortOrder": 0,
        "moods": [
          "quiet",
          "still"
        ],
        "instruments": [
          "pads"
        ],
        "fullKey": null,
        "previewKey": null
      }
    ]
  }
]
